name: Build and push Docker image

# Trigger: When code is pushed to the master branch
on:
  push:
    branches: [ 'master' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest              # Use the Github's latest Ubuntu runner

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (for building multi-platform images & Advanced caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub access token stored in GitHub Secrets

      # 4. Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .                           # Context is the root of the repository
          file: ./Dockerfile                   # Path to the Dockerfile
          push: true                          # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/my-angular20-app:latest  # Replace with your Docker Hub username
