name: Build and push Docker image

# Trigger: When code is pushed to the master branch
on:
  push:
    branches: [ 'master' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest              # Use the Github's latest Ubuntu runner

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0                  # Fetch all history for all branches and tags

      #2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'               # Specify Node.js version 20
          cache: 'npm'                     # Cache npm dependencies

      #3. Install project dependencies
      - name: Install Dependencies
        run: npm install                   # Install npm dependencies

      #4. Install browser for CI tests ---
      - name: Install Playwright Browsers
        run: npx playwright install chromium        # Install Playwright browsers for testing

      #5. Quality check with linting
      - name: Run Linting
        run: npm run lint                  # Run linting script defined in package.json

      #6. Quality check with tests
      - name: Run Unit Tests
        run: npx ng test --watch=false --browsers=chromium                      # Run test script defined in package.json

      #7. Quality Guard: SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-generated GitHub token
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # SonarCloud token stored in GitHub Secrets
        with:
          args: >
            -Dsonar.organization=dheerajraja111
            -Dsonar.projectKey=dheerajraja111_my-angular20-app
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info

      #8. Set up Docker Buildx (for building multi-platform images & Advanced caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #9 Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub access token stored in GitHub Secrets

      #10. Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .                           # Context is the root of the repository
          file: ./Dockerfile                   # Path to the Dockerfile
          push: true                          # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/my-angular20-app:latest  # Replace with your Docker Hub username
